version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: trippostdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  mongodb:
    image: mongo:5.0
    container_name: tripmogodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kero2001
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


volumes:
  postgres_data:
  mongo_data:

networks:
  app-network:
    driver: bridge