version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: trip_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kero2001
      POSTGRES_DB: trip_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  mongodb:
    image: mongo:5.0
    container_name: trip_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network


volumes:
  postgres_data:
  mongo_data:

networks:
  app-network:
    driver: bridge